[package]
name = "dioxus_components"
version = "0.1.0"
edition = "2021"
authors = ["Louis Truchelut"]

[lib]
name = "dioxus_components"
path = "src/lib.rs"

[dependencies]

dioxus-components-macro = { path = "./dioxus-components-macro" }
log = "0.4.17"
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "f76c80bab20f71acc14b330f3b565926b352cb3f", features = ["web"] }
dioxus-logger = "0.4.1"
manganis = "0.2.2"
console = "0.15.8"
tailwind_fuse = { version = "0.3.1", features = ["variant"] }
web-sys = {version = "0.3.69", features = ["Element"]}

serde_json = "1.0.1"

form_builder = { git = "ssh://github.com/ZialeOrg/form_builder.git", branch = "add-table" }
slugify = "0.1.0"

gloo-timers = { version = "0.3.0", features = ["futures"] }
chrono = "0.4.38"