[package]
name = "dioxus_components"
version = "0.1.0"
edition = "2021"
authors = ["Louis Truchelut"]

[lib]
name = "dioxus_components"
path = "src/lib.rs"

[dependencies]

dioxus-components-macro = { path = "./dioxus-components-macro" }
log = "0.4.17"
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "0eb16f27d4a66f654d18fe46fa7f0d50180a1a28", features = ["web"] }
dioxus-logger = "0.4.1"
manganis = "0.2.2"
console = "0.15.8"
tailwind_fuse = { version = "0.2.0", features = ["variant"] }
web-sys = {version = "0.3.69", features = ["Element"]}

serde_json = "1.0.1"

form_builder = { git = "ssh://github.com/ZialeOrg/form_builder.git", branch = "add-table" }
slugify = "0.1.0"
