[package]

name = "dioxus_components"
version = "0.1.0"
edition = "2021"
authors = ["Louis Truchelut"]

[lib]

name = "dioxus_components"
path = "src/lib.rs"

[features]

theme = []

[dependencies]

dioxus-components-macro = { path = "./dioxus-components-macro" }
log = "0.4.22"
dioxus = { version = "0.5.6", features = ["web"] }
dioxus-logger = "0.4.1"
manganis = "0.2.2"
console = "0.15.8"
tailwind_fuse = { version = "0.3.1", features = ["variant"] }
web-sys = {version = "0.3.76", features = ["Element"]}

serde_json = "1.0.133"

slugify = "0.1.0"

gloo-timers = { version = "0.3.0", features = ["futures"] }
chrono = "0.4.39"
