workspace = { members = ["component-derive"] }
[package]
name = "dioxus_components_bin"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "dioxus_comps"

[dependencies]
futures = "0.3.30"
reqwest = { version = "0.11.24", features = ["json"] }
serde = "1.0.196"
serde_json = "1.0.113"
console_error_panic_hook = "0.1.7"
log = "0.4.17"
tracing-wasm = "0.2.1"
tracing = "0.1.40"

dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "7eccc7a104df013b06c104fc1275450d2747e78c", features = ["web", "router"] }
dioxus-logger = "0.4.1"
manganis = "0.2.1"
console = "0.15.8"
tailwind_fuse = { version = "0.2.0", features = ["variant"] }

component-derive = { path = "component-derive" }
