workspace = { members = ["props-component-macro"] }

[package]
name = "dioxus_components"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "dioxus_comps"

[dependencies]
log = "0.4.17"

dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "c9ab09b3480ba2ad3b77d16c5e86382a62258194", features = ["web"] }
dioxus-logger = "0.4.1"
manganis = "0.2.1"
console = "0.15.8"
tailwind_fuse = { version = "0.2.0", features = ["variant"] }
web-sys = {version = "0.3.69", features = ["Element"]}
props-component-macro = { path = "props-component-macro" }

form_builder = { git = "ssh://github.com/ZialeOrg/form_builder.git", branch = "feat-version1.0" }
slugify = "0.1.0"
