name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    environment: cargo

    steps:
      - uses: actions/checkout@master
        with:
          # get git tags info
          fetch-depth: 0

      - name: Run publish-action
        uses: tu6ge/publish-action@v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          TAG_PREFIX: "v"
