name: Publish to Cargo

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish'

    environment: cargo

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-release
        run: cargo binstall cargo-release

      - name: Release (execute)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          cargo release ${{ steps.bump.outputs.level }} --execute --no-confirm
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
